import os
from io import BytesIO
from datetime import datetime
from celery import shared_task
from flask_mail import Message
from models import db, mail
from models.application import Application
from models.students import Student
from models.placement import PlacementDrive


def _build_certificate_html(participant_name, event_name, organizer_name, event_date):
    return f"""
    <html>
    <body style="font-family: Georgia, serif; padding: 60px; text-align: center; border: 8px double #2d8cf0; margin: 30px;">
        <div style="padding: 40px;">
            <h1 style="color: #2d8cf0; font-size: 36px; margin-bottom: 5px;">CERTIFICATE OF PARTICIPATION</h1>
            <hr style="border: 1px solid #2d8cf0; width: 60%;">
            <p style="font-size: 18px; margin-top: 30px;">This is to certify that</p>
            <h2 style="font-size: 28px; color: #333; margin: 10px 0;">{participant_name}</h2>
            <p style="font-size: 18px;">has successfully participated in</p>
            <h3 style="font-size: 24px; color: #2d8cf0; margin: 10px 0;">{event_name}</h3>
            <p style="font-size: 16px; color: #555;">organized by <strong>{organizer_name}</strong></p>
            <p style="font-size: 16px; color: #555;">on <strong>{event_date}</strong></p>
            <div style="margin-top: 60px;">
                <p style="font-size: 12px; color: #999;">Auto-generated by Event Management Portal</p>
            </div>
        </div>
    </body>
    </html>
    """


@shared_task(ignore_result=False)
def dispatch_certificates(event_id):
    drive = PlacementDrive.query.get(event_id)
    if not drive:
        return "Event not found"

    registrations = Application.query.filter_by(drive_id=event_id, is_present=True, certificate_sent=False).all()
    if not registrations:
        return "No eligible attendees for certificates"

    sent_count = 0
    for reg in registrations:
        student = Student.query.get(reg.student_id)
        if not student:
            continue

        event_date = drive.application_deadline.strftime('%d %b, %Y') if drive.application_deadline else datetime.now().strftime('%d %b, %Y')
        html = _build_certificate_html(student.name, drive.job_title, drive.organizer_name, event_date)

        try:
            from xhtml2pdf import pisa
            pdf_buffer = BytesIO()
            pisa.CreatePDF(html, dest=pdf_buffer)
            pdf_buffer.seek(0)

            msg = Message(
                f"Certificate of Participation - {drive.job_title}",
                recipients=[student.email]
            )
            msg.body = f"Hi {student.name},\n\nPlease find attached your certificate of participation for {drive.job_title}.\n\nBest regards,\nEvent Management Team"
            msg.attach(
                f"Certificate_{student.name.replace(' ', '_')}.pdf",
                "application/pdf",
                pdf_buffer.read()
            )
            mail.send(msg)

            reg.certificate_sent = True
            sent_count += 1
        except Exception as e:
            print(f"[ERROR] Certificate for {student.name} failed: {str(e)}")

    db.session.commit()
    return f"Sent {sent_count} certificates for event '{drive.job_title}'"
